2025-02-16 22:03:29.645646: I tensorflow/core/util/port.cc:153] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.
2025-02-16 22:03:30.334259: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:477] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
E0000 00:00:1739743410.592895  572647 cuda_dnn.cc:8310] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
E0000 00:00:1739743410.663838  572647 cuda_blas.cc:1418] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2025-02-16 22:03:31.328379: I tensorflow/core/platform/cpu_feature_guard.cc:210] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 AVX512F AVX512_VNNI FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
Traceback (most recent call last):
  File "/dcs/21/u2104990/Documents/324/runondcs/run.py", line 4, in <module>
    training = tf.data.Dataset.load('/dcs/large/u2104990/runondcs/training_data/')
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dcs/21/u2104990/.local/lib/python3.12/site-packages/tensorflow/python/data/ops/dataset_ops.py", line 1846, in load
    return load_op._load(
           ^^^^^^^^^^^^^^
  File "/dcs/21/u2104990/.local/lib/python3.12/site-packages/tensorflow/python/data/ops/load_op.py", line 68, in _load
    element_spec = _load_element_spec(path)
                   ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/dcs/21/u2104990/.local/lib/python3.12/site-packages/tensorflow/python/data/ops/load_op.py", line 155, in _load_element_spec
    raise errors.NotFoundError(
tensorflow.python.framework.errors_impl.NotFoundError: tf.data snapshot element_spec file not found: /dcs/large/u2104990/runondcs/training_data/dataset_spec.pb.
